### ISSUE TITLE
More quotes

### ISSUE THREAD

**Issue by ankile** [KaranDahiya/philosophy-quotes-API#4]
This API has such great potential and I feel like the only thing lacking is a much larger archive of quotes to sample from. Is this something that's on the roadmap?

**Comment by KaranDahiya** [comment]
I know this is an incredibly late response, but yes, I am finally going to add more quotes to this API and potentially more categorical options.

**Comment by KaranDahiya** [comment]
There are now over 100 quotes available, and more will likely be added in the future. Closing this issue.
